healthwatch-forwarder/boshhealth_instance_count: 1
healthwatch-forwarder/boshtasks_instance_count: 2
healthwatch-forwarder/canary_instance_count: 2
healthwatch-forwarder/cli_instance_count: 2
healthwatch-forwarder/ingestor_instance_count: 4
healthwatch-forwarder/opsman_instance_count: 2
healthwatch-forwarder/publish_to_eva: true
healthwatch-forwarder/worker_instance_count: 1
delete-space_pre_delete_state: default
push-apps_post_deploy_state: default
smoke-tests_post_deploy_state: default
healthwatch-forwarder_instance_type: automatic
healthwatch-forwarder_instances: automatic
healthwatch-forwarder_persistent_disk_size: automatic
mysql_instance_type: automatic
mysql_instances: automatic
mysql_persistent_disk_size: automatic
redis_instance_type: automatic
redis_instances: automatic
redis_persistent_disk_size: automatic
