opsman-configuration:
  vsphere:
    vcenter:
      url: ((vcenter_hostname)) # in credhub
      username: ((vcenter_userid)) # in credhub
      password: ((vcenter_password)) # in credhub
      datastore: ((vsphere_datastore)) # in vars file
      datacenter: ((vsphere_datacenter)) # in vars file
      resource_pool: ((vsphere_resource_pool)) # in vars file
      folder: ((vsphere_vms_folder)) # in vars file
      insecure: 1                            # 1 insecure, 0 secure
    disk_type: thin                          # example: thin|thick
    private_ip: ((opsman_private_ip))
    dns: ((dns))
    ntp: ((ntp))                    # example: ntp.ubuntu.com
    ssh_password: ((opsman_ssh_password))
    ssh_public_key: ((opsman_ssh.public_key))
    hostname: ((opsman_host))
    network: ((infrastructure_network))               # vcenter network to deploy to
    netmask: ((opsman_netmask))
    gateway: ((infrastructure_gateway))
    vm_name: ((opsman_vm_name))
