---
target: ((opsman_host))
connect-timeout: 30            # default 5
request-timeout: 1800          # default 1800
skip-ssl-validation: true     # default false
username: ((opsman_userid))
password: ((opsman_password))
decryption-passphrase: ((opsman_decryption_passphrase))
